### ISSUE TITLE
Enhancement: Android version? 

### ISSUE THREAD

**Issue by djambo** [keijiro/NDILiteSenderPlugin#1]
First of all, thank you for this amazing plugin, it simplified my workflow drastically. I am just wondering here, by any chance are you planning on having this working on Android as well?

**Comment by keijiro** [comment]
I'm also interested in Android support, but I have no recent Android device that has enough capability to run NDI.

Anyway, thanks for the input. I understood that there is some demand for it.

**Comment by keijiro** [comment]
Just out of curiosity, which Android device are you going to use?

**Comment by djambo** [comment]
I was actually about to tell you. It's called [Orbbec Parsee](https://orbbec3d.com/products/): 

specs:
Quad-core Cortex A17 Up to 1.8GHz
GPU | Mali-T7 600MHz
RAM | 2GB DDR3
Wi-Fi | Built-in, 802.11 2.4GHz
Bluetooth | Built-in

**Comment by keijiro** [comment]
Thanks for the information. It looks interesting.
