### ISSUE TITLE
UnityException: SetTexture failed

### ISSUE THREAD

**Issue by mapa0644** [keijiro/NDILiteSenderPlugin#2]
The test-project only sends an empty NDI-stream with the UnityException: SetTexture failed on every frame, while the graphic is rendered correctly in Unity

**Comment by keijiro** [comment]
Thanks for reporting. Could you send the whole error log? I'd like to look into the details.

**Comment by mapa0644** [comment]
Thank you for the quick response. Here is the log.
[Editor.log](https://github.com/keijiro/NDILiteSenderPlugin/files/2115504/Editor.log)

**Comment by keijiro** [comment]
It seems that Unity Editor is running in OpenGL mode. This plugin only supports Metal.

Is your device (MacBook?) compatible with Metal? If so, please try to change Editor to Metal mode.

If your device is not compatible with Metal, there is nothing we can do about it.

**Comment by mapa0644** [comment]
The window says OpenGL while the Metal Editor Support checkbox is marked. Is this correct?

The MacBook runs on Sierra 10.12.6, so compatibilty should not be the issue.

Here is a screenshot of the project settings: 
![player settings](https://user-images.githubusercontent.com/19222007/41668625-079eb3d8-74b0-11e8-9127-a2900627d4e5.jpeg)

**Comment by keijiro** [comment]
From the Editor log, I thought you're using MacBookPro8,1 -- MacBookPro 2011 or 2012. If you're using one of the MBP 2011 earlier models with Intel HD Graphics 3000, it may not support Metal.

https://en.wikipedia.org/wiki/Metal_(API)#Supported_GPUs

I'm not sure what the best way to check Metal support is, someone suggests using GLview.

https://www.tonymacx86.com/threads/is-there-a-way-to-check-for-metal-compatibility.201882
