### ISSUE TITLE
TargetGuidByName Deprecated

### ISSUE THREAD

**Issue by cvasquez-github** [keijiro/NDILiteSenderPlugin#3]
Just a minor thing on the PbxModifier.cs file

_string target = proj.TargetGuidByName("Unity-iPhone");_

Should be replaced with:

_string target = proj.GetUnityMainTargetGuid();_

for newer versions fo Unity, like 2020.1

**Comment by keijiro** [comment]
This issue was fixed in KlakNDI https://github.com/keijiro/KlakNDI
